### ISSUE TITLE
Not compatible with latest versions of libraries?

### ISSUE THREAD

**Issue by donnielrt** [AndrewKeig/node-plates#1]
Firstly, thanks for your work on this boilerplate, it looks like it might be very useful!

I'm pretty new to node/express, so forgive me if this is not a valid issue. I am running node v0.8.4 with express 3.0.0rc1 on Ubuntu 12.04 , and I'm running into problems running the server. I've tried both npm install node-plates, as well as cloning your repository.

Both times I get errors in the code. With git clone, the error is: 

TypeError: Object #<ServerResponse> has no method 'format'
    at exports.index (/var/www/routes/home.js:17:13)
    at Object.exports.find_article_by_type (/var/www/data/query.js:15:5)
    at Router.exports.index (/var/www/routes/home.js:10:13)
    at done (/var/www/node_modules/express/lib/router/index.js:250:22)
    at middleware (/var/www/node_modules/express/lib/router/index.js:244:9)
    at param (/var/www/node_modules/express/lib/router/index.js:227:11)
    at pass (/var/www/node_modules/express/lib/router/index.js:232:7)
    at Router._dispatch (/var/www/node_modules/express/lib/router/index.js:255:5)
    at Object.middleware [as handle](/var/www/node_modules/express/lib/router/index.js:45:10)
    at next (/var/www/node_modules/express/node_modules/connect/lib/http.js:204:15)

Is node-plates compatible with the latest versions of the libraries as shown in package.json?

**Comment by AndrewKeig** [comment]
Hey; our package.json file was out of date; I have updated the package.json file to reflect what we are currently able to support; node-plates is working with node version 8.4; express 3.0.0alpha1; it should work with RC.   I have also republished to NPM so this should be working again.

**Comment by donnielrt** [comment]
Awesome! Will check it out tonight.
